import React, { useEffect, useMemo, useState } from 'react';
import { BookOpen, Cat, Check, ChevronLeft, ChevronRight, Download, FolderHeart, ImageOff, KeyRound, LayoutGrid, LogIn, LogOut, Maximize2, Menu, PlayCircle, RefreshCw, Search, Settings2, Share2, Sparkles, User as UserRound, X } from 'lucide-react';

const REFRESH_MS = 5 * 60 * 1000;
const DEMO_CATS = [
  { id: 'CAT-26091', breed: '英短', color: '金渐层', gender: '公', age: '2个月', vaccine: '1针', description: '圆脸大眼，毛色层次自然，性格安静亲人。', price: 899, city: '上海', images: [], videos: [] },
  { id: 'CAT-26092', breed: '布偶', color: '海双', gender: '母', age: '3个月', vaccine: '2针', description: '蓝眼睛清澈，毛量丰厚，整体甜美乖巧。', price: 1680, city: '杭州', images: [], videos: [] },
  { id: 'CAT-26093', breed: '缅因猫', color: '银虎斑', gender: '公', age: '3个月', vaccine: '1针', description: '耳尖毛明显，骨量感好，站姿精神又大方。', price: 2380, city: '苏州', images: [], videos: [] },
  { id: 'CAT-26094', breed: '拿破仑', color: '纯白', gender: '公', age: '2个月', vaccine: '1针', description: '雪白长毛，圆脸粉鼻，抬爪时活泼可爱。', price: 1280, city: '上海', images: [], videos: [] },
];
const money = value => value == null ? '请咨询' : `¥${Math.round(value).toLocaleString('zh-CN')}`;
const ageText = value => { const v = String(value ?? '').trim(); return v && /^\d+(?:\.\d+)?$/.test(v) ? `${v}个月` : v; };
const load = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } };
const save = (key, value) => localStorage.setItem(key, JSON.stringify(value));
function quote(base, profile, override) { if (override !== '' && Number.isFinite(Number(override))) return Math.max(0, Number(override)); if (base == null) return null; let value = profile.mode === 'rate' ? base * (1 + Number(profile.markup || 0) / 100) : base + Number(profile.markup || 0); if (profile.ending === '99') value = Math.max(99, Math.ceil((value + 1) / 100) * 100 - 1); if (profile.ending === '10') value = Math.round(value / 10) * 10; if (profile.ending === '100') value = Math.round(value / 100) * 100; return Math.round(value); }

export default function App() {
  const [signedIn,setSignedIn]=useState(()=>sessionStorage.getItem('sales-demo-session')==='1'),[login,setLogin]=useState(null);
  const requireAuth=(action,reason='登录后才能使用这项功能')=>{if(signedIn)return action();setLogin({action,reason});};
  const enter=()=>{sessionStorage.setItem('sales-demo-session','1');setSignedIn(true);const action=login?.action;setLogin(null);action?.();};
  const logout=()=>{sessionStorage.removeItem('sales-demo-session');setSignedIn(false);};
  return <><Workspace signedIn={signedIn} requireAuth={requireAuth} onLogin={()=>setLogin({reason:'登录后可保存货源、报价和销售资料'})} onLogout={logout}/>{login&&<Login reason={login.reason} onEnter={enter} close={()=>setLogin(null)}/>}</>;
}

function Login({ onEnter, close, reason }) {
  const [account, setAccount] = useState('sales-demo'), [password, setPassword] = useState(''), [error, setError] = useState('');
  const submit = e => { e.preventDefault(); if (!account.trim() || !password.trim()) return setError('请输入管理员分配的账号和密码'); onEnter(); };
  return <div className="fixed inset-0 z-[100] bg-stone-950/55 p-4 grid place-items-center" onMouseDown={e=>e.target===e.currentTarget&&close()}><form onSubmit={submit} className="relative w-full max-w-md rounded-[28px] bg-white border border-stone-200 p-7 sm:p-9 shadow-2xl"><button type="button" onClick={close} className="absolute right-5 top-5 text-stone-400"><X size={19}/></button><div className="w-11 h-11 rounded-2xl bg-[#e89a45] text-white grid place-items-center"><UserRound size={22}/></div><p className="mt-6 text-sm text-emerald-800 font-semibold">销售身份验证</p><h2 className="mt-1 text-2xl font-semibold text-stone-900">登录后继续</h2><p className="mt-2 text-sm text-stone-500">{reason}</p><button type="button" onClick={()=>setError('Passkey 将在接入正式账号服务后启用；当前请使用演示账号。')} className="mt-6 w-full rounded-xl border border-stone-300 py-3 font-semibold flex items-center justify-center gap-2"><KeyRound size={18}/>使用指纹、面容或设备解锁</button><div className="my-5 flex items-center gap-3 text-xs text-stone-400"><span className="h-px flex-1 bg-stone-200"/>或使用管理员账号<span className="h-px flex-1 bg-stone-200"/></div><label className="block text-sm font-medium">销售账号<input value={account} onChange={e=>setAccount(e.target.value)} className="mt-2 w-full rounded-xl border border-stone-300 px-4 py-3 outline-none focus:border-emerald-700" /></label><label className="block mt-4 text-sm font-medium">密码<input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="演示时输入任意内容" className="mt-2 w-full rounded-xl border border-stone-300 px-4 py-3 outline-none focus:border-emerald-700" /></label>{error&&<p className="mt-3 text-sm text-amber-700">{error}</p>}<button className="mt-6 w-full rounded-xl bg-[#183f32] py-3.5 font-semibold text-white hover:bg-[#102f25]">登录并继续</button><p className="mt-4 text-center text-xs leading-5 text-stone-400">不开放自行注册，销售身份由管理员统一授权。</p></form></div>;
}

function Workspace({ signedIn, requireAuth, onLogin, onLogout }) {
  const [cats,setCats]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState('catalog'),[mobileNav,setMobileNav]=useState(false);
  const [saved,setSaved]=useState(()=>load('sales-saved',[])),[selected,setSelected]=useState([]),[prices,setPrices]=useState(()=>load('sales-prices',{}));
  const [profile,setProfile]=useState(()=>load('sales-profile',{name:'麦麦',phone:'微信：maimai-cat',mode:'fixed',markup:800,ending:'99'}));
  const [filters,setFilters]=useState({query:'',breed:'',gender:'',city:'',min:'',max:''}),[settings,setSettings]=useState(false),[share,setShare]=useState(false),[notice,setNotice]=useState('');
  const [playing,setPlaying]=useState(null),[preview,setPreview]=useState(null);
  const refresh=async signal=>{setLoading(true);try{const r=await fetch('/api/public-cats',{cache:'no-cache',signal});const b=await r.json();if(!r.ok||!b.success||!Array.isArray(b.data))throw new Error();setCats(b.data);setError('');}catch(e){if(e.name!=='AbortError'){setError('暂时无法读取线上猫源，当前显示演示数据。');setCats(DEMO_CATS);}}finally{if(!signal?.aborted)setLoading(false);}};
  useEffect(()=>{const c=new AbortController();refresh(c.signal);const t=setInterval(()=>!document.hidden&&refresh(c.signal),REFRESH_MS);return()=>{c.abort();clearInterval(t);};},[]);
  useEffect(()=>save('sales-saved',saved),[saved]); useEffect(()=>save('sales-prices',prices),[prices]); useEffect(()=>save('sales-profile',profile),[profile]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),2200);return()=>clearTimeout(t);},[notice]);
  const visibleCats=tab==='saved'?cats.filter(c=>saved.includes(c.id)):cats;
  const breeds=[...new Set(cats.map(c=>c.breed).filter(Boolean))].sort(),cities=[...new Set(cats.map(c=>c.city).filter(Boolean))].sort();
  const filtered=useMemo(()=>visibleCats.filter(c=>{const q=filters.query.trim().toLowerCase(),p=c.price;return(!q||[c.id,c.breed,c.color].some(v=>String(v||'').toLowerCase().includes(q)))&&(!filters.breed||c.breed===filters.breed)&&(!filters.gender||c.gender===filters.gender)&&(!filters.city||c.city===filters.city)&&(filters.min===''||(p!=null&&p>=Number(filters.min)))&&(filters.max===''||(p!=null&&p<=Number(filters.max)));}),[visibleCats,filters]);
  const toggleSaved=id=>requireAuth(()=>setSaved(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]),'登录后才能把猫咪长期保存到“我的货源”'),toggleSelected=id=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
  const openTab=id=>{const action=()=>{setTab(id);setMobileNav(false);};id==='catalog'?action():requireAuth(action,id==='saved'?'登录后才能查看长期保存的货源':'登录后才能制作和导出销售资料');};
  const selectedCats=cats.filter(c=>selected.includes(c.id));
  const exportCsv=()=>{const rows=[['猫咪ID','品种','性别','年龄','城市','销售价'],...selectedCats.map(c=>[c.id,c.breed,c.gender,ageText(c.age),c.city||'',quote(c.price,profile,prices[c.id]??'')])];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`销售猫源-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);setNotice('表格已导出');};
  return <div className="min-h-screen bg-[#f7f7f5] text-stone-800">
    <header className="sticky top-0 z-30 bg-white/95 border-b border-stone-200 backdrop-blur"><div className="max-w-[1500px] mx-auto px-4 sm:px-6 h-16 flex items-center justify-between"><div className="flex items-center gap-3"><button onClick={()=>setMobileNav(!mobileNav)} className="lg:hidden"><Menu/></button><span className="w-9 h-9 rounded-xl bg-[#e89a45] text-white grid place-items-center"><Cat size={21}/></span><div><b>猫源销售系统</b><small className="hidden sm:block text-[11px] text-stone-400">销售工作台 · V1 预览</small></div></div><div className="flex items-center gap-2"><button onClick={()=>requireAuth(()=>setSettings(true),'登录后才能保存个人报价和联系方式')} className="rounded-xl border border-stone-200 px-3 py-2 text-sm flex gap-2 items-center"><Settings2 size={16}/><span className="hidden sm:inline">报价设置</span></button>{signedIn?<button onClick={onLogout} className="rounded-xl px-3 py-2 text-sm text-stone-500 flex items-center gap-2" title="退出"><LogOut size={17}/><span className="hidden sm:inline">退出</span></button>:<button onClick={onLogin} className="rounded-xl bg-[#183f32] px-3 py-2 text-sm text-white flex items-center gap-2"><LogIn size={17}/>登录</button>}</div></div></header>
    {!signedIn&&<div className="border-b border-amber-200 bg-amber-50 px-4 py-2 text-center text-xs text-amber-800">当前为游客模式：可浏览、筛选和临时勾选；供货价与个人功能登录后显示。</div>}
    <div className="max-w-[1500px] mx-auto lg:grid lg:grid-cols-[220px_1fr] min-h-[calc(100vh-64px)]"><aside className={`${mobileNav?'block':'hidden'} lg:block border-r border-stone-200 bg-white p-4`}><nav className="space-y-1">{[['catalog',LayoutGrid,'猫源库'],['saved',FolderHeart,'我的货源'],['materials',Sparkles,'素材工具']].map(([id,Icon,label])=><button key={id} onClick={()=>openTab(id)} className={`w-full flex items-center justify-between rounded-xl px-3 py-3 text-sm ${tab===id?'bg-[#edf4f0] text-[#173e31] font-semibold':'hover:bg-stone-50'}`}><span className="flex items-center gap-3"><Icon size={18}/>{label}</span>{id==='saved'&&<em className="not-italic text-xs">{signedIn?saved.length:<KeyRound size={13}/>}</em>}</button>)}</nav><div className={`mt-8 rounded-2xl p-4 ${signedIn?'bg-[#183f32] text-white':'border border-stone-200 bg-stone-50'}`}><p className={`text-xs ${signedIn?'text-white/60':'text-stone-400'}`}>{signedIn?'当前销售':'游客使用中'}</p><b className="mt-1 block">{signedIn?profile.name:'无需登录即可找猫'}</b><p className={`mt-3 text-xs ${signedIn?'text-white/70':'text-stone-500'}`}>{signedIn?`默认加价：${profile.mode==='rate'?`${profile.markup}%`:`${profile.markup}元`}`:'勾选内容会保留到登录完成'}</p></div><a href="/guide/" className="mt-4 flex items-center gap-2 px-3 py-2 text-xs text-stone-500"><BookOpen size={15}/>销售手册</a></aside>
      <main className="p-4 sm:p-7 min-w-0">{tab==='materials'?<Materials selected={selectedCats} profile={profile} prices={prices} onExport={exportCsv} onShare={()=>setShare(true)}/>:<><div className="flex flex-wrap justify-between items-end gap-4"><div><p className="text-sm text-emerald-800 font-semibold">{tab==='saved'?'PERSONAL STOCK':'LIVE CATALOG'}</p><h1 className="mt-1 text-2xl font-semibold">{tab==='saved'?'我的货源':'实时猫源库'}</h1><p className="mt-1 text-sm text-stone-500">{tab==='saved'?'收藏常用货源并设置自己的售价':'当前在售猫咪，库存变化前请再次确认'}</p></div><button onClick={()=>refresh()} className="flex items-center gap-2 text-sm text-stone-500"><RefreshCw size={16} className={loading?'animate-spin':''}/>刷新</button></div><Filters value={filters} set={setFilters} breeds={breeds} cities={cities} signedIn={signedIn}/>{error&&<p className="mb-4 rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-800">{error}</p>}<div className="mb-4 flex items-center justify-between text-sm text-stone-500"><span>找到 {filtered.length} 只猫咪</span>{selected.length>0&&<button onClick={()=>openTab('materials')} className="rounded-xl bg-[#183f32] px-4 py-2 text-white">已选 {selected.length} 只 · 去制作资料</button>}</div>{filtered.length===0?<Empty saved={tab==='saved'}/>:<div className="grid sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4 gap-5">{filtered.map(cat=><CatCard key={cat.id} cat={cat} signedIn={signedIn} saved={saved.includes(cat.id)} selected={selected.includes(cat.id)} salePrice={quote(cat.price,profile,prices[cat.id]??'')} custom={prices[cat.id]??''} setCustom={v=>setPrices(p=>({...p,[cat.id]:v}))} onSave={()=>toggleSaved(cat.id)} onSelect={()=>toggleSelected(cat.id)} onPlay={()=>setPlaying(cat)} onPreview={()=>setPreview(cat)}/>)}</div>}</>}</main>
    </div>{settings&&<PriceSettings profile={profile} set={setProfile} close={()=>setSettings(false)}/>} {share&&<SharePreview cats={selectedCats} profile={profile} prices={prices} close={()=>setShare(false)} notify={setNotice}/>} {playing&&<Video cat={playing} close={()=>setPlaying(null)}/>} {preview&&<Photo cat={preview} close={()=>setPreview(null)}/>} {notice&&<div className="fixed z-[90] bottom-5 left-1/2 -translate-x-1/2 bg-stone-900 text-white rounded-xl px-4 py-3 text-sm shadow-xl flex gap-2"><Check size={17}/>{notice}</div>}
  </div>;
}

function Filters({value,set,breeds,cities,signedIn}){const field=(k,v)=>set(x=>({...x,[k]:v}));return <div className={`my-6 grid grid-cols-2 md:grid-cols-3 ${signedIn?'xl:grid-cols-6':'xl:grid-cols-4'} gap-3 rounded-2xl border border-stone-200 bg-white p-4`}><label className="col-span-2 md:col-span-1 relative"><Search size={16} className="absolute left-3 top-3 text-stone-400"/><input value={value.query} onChange={e=>field('query',e.target.value)} placeholder="编号、品种、花色" className="w-full rounded-xl bg-stone-50 py-2.5 pl-9 pr-3 text-sm"/></label><Select value={value.breed} set={v=>field('breed',v)} values={breeds} label="全部品种"/><Select value={value.gender} set={v=>field('gender',v)} values={['公','母']} label="不限性别"/><Select value={value.city} set={v=>field('city',v)} values={cities} label="全部城市"/>{signedIn&&<><input type="number" value={value.min} onChange={e=>field('min',e.target.value)} placeholder="最低供货价" className="rounded-xl bg-stone-50 px-3 py-2.5 text-sm"/><input type="number" value={value.max} onChange={e=>field('max',e.target.value)} placeholder="最高供货价" className="rounded-xl bg-stone-50 px-3 py-2.5 text-sm"/></>}</div>}
function Select({value,set,values,label}){return <select value={value} onChange={e=>set(e.target.value)} className="rounded-xl bg-stone-50 px-3 py-2.5 text-sm"><option value="">{label}</option>{values.map(v=><option key={v}>{v}</option>)}</select>}
function Empty({saved}){return <div className="rounded-2xl border border-dashed border-stone-300 py-20 text-center text-stone-400"><FolderHeart className="mx-auto mb-3"/>{saved?'还没有加入我的货源':'没有符合条件的猫咪'}</div>}
function CatCard({cat,signedIn,saved,selected,salePrice,custom,setCustom,onSave,onSelect,onPlay,onPreview}){const image=cat.images?.[0]||cat.image;return <article className={`rounded-2xl overflow-hidden border bg-white shadow-sm ${selected?'border-emerald-700 ring-2 ring-emerald-700/10':'border-stone-200'}`}><div className="relative aspect-[4/3] bg-[#f2ede5]">{image?<img src={image} className="h-full w-full object-cover" alt={cat.breed}/>:<div className="h-full grid place-items-center text-stone-300"><ImageOff/></div>}<button onClick={onSelect} title="临时勾选" className={`absolute left-3 top-3 w-7 h-7 rounded-lg grid place-items-center ${selected?'bg-emerald-700 text-white':'bg-white/90 text-stone-400'}`}>{selected&&<Check size={17}/>}</button><button onClick={onSave} className={`absolute right-3 top-3 rounded-lg px-2.5 py-1.5 text-xs font-semibold ${saved&&signedIn?'bg-[#183f32] text-white':'bg-white/90'}`}>{signedIn?(saved?'已加入':'加入货源'):<span className="flex items-center gap-1"><KeyRound size={12}/>保存</span>}</button>{cat.videos?.length>0&&<button onClick={onPlay} className="absolute right-3 bottom-3 rounded-lg bg-white/90 p-2"><PlayCircle size={18}/></button>}{image&&<button onClick={onPreview} className="absolute left-3 bottom-3 rounded-lg bg-white/90 p-2"><Maximize2 size={17}/></button>}</div><div className="p-4"><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{cat.breed||'猫咪'} · {cat.color||'花色待补充'}</h3><p className="mt-1 text-xs text-stone-500">{cat.gender||'待补充'} · {ageText(cat.age)||'年龄待补充'} · {cat.city||'城市待补充'}</p></div><span className="text-xs text-stone-400">{cat.id}</span></div><p className="mt-3 line-clamp-2 min-h-[40px] text-sm leading-5 text-stone-500">{cat.description||'暂无描述'}</p>{signedIn?<><div className="mt-4 grid grid-cols-2 gap-3 border-t border-stone-100 pt-3"><div><small className="text-stone-400">平台供货价</small><b className="block">{money(cat.price)}</b></div><div><small className="text-stone-400">我的销售价</small><b className="block text-[#c96f23]">{money(salePrice)}</b></div></div>{saved&&<input type="number" value={custom} onChange={e=>setCustom(e.target.value)} placeholder="输入自定义售价" className="mt-3 w-full rounded-xl bg-stone-50 px-3 py-2 text-sm"/>}</>:<div className="mt-4 flex items-center gap-2 border-t border-stone-100 pt-3 text-xs text-stone-400"><KeyRound size={14}/>登录销售账号后查看供货价与个人报价</div>}</div></article>}

function Materials({selected,profile,prices,onExport,onShare}){return <div><p className="text-sm font-semibold text-emerald-800">SALES MATERIALS</p><h1 className="mt-1 text-2xl font-semibold">销售素材工具</h1><p className="mt-1 text-sm text-stone-500">把选中的猫咪整理成可以直接发给客户的资料。</p><div className="mt-7 grid md:grid-cols-3 gap-4">{[[Download,'导出销售表格','编号、资料与个人报价整理为 CSV',onExport],[Sparkles,'批量销售图','按统一模板生成带报价和联系方式的图片',()=>alert('界面预览：下一阶段接入图片批量生成')],[Share2,'客户展示页','预览客户看到的多猫展示页',onShare]].map(([Icon,title,text,fn])=><button key={title} onClick={fn} disabled={!selected.length} className="text-left rounded-2xl border border-stone-200 bg-white p-5 disabled:opacity-40"><Icon className="text-[#c96f23]"/><b className="mt-5 block">{title}</b><p className="mt-2 text-sm leading-6 text-stone-500">{text}</p></button>)}</div><div className="mt-7 rounded-2xl border border-stone-200 bg-white"><div className="border-b border-stone-100 p-4 flex justify-between"><b>已选择 {selected.length} 只</b><span className="text-sm text-stone-400">销售：{profile.name}</span></div>{selected.length===0?<p className="p-12 text-center text-stone-400">请先回到猫源库选择猫咪</p>:<div className="divide-y divide-stone-100">{selected.map(c=><div key={c.id} className="p-4 flex items-center justify-between gap-4"><div><b>{c.breed} · {c.color}</b><p className="text-xs text-stone-400">{c.id} · {c.gender} · {ageText(c.age)}</p></div><b className="text-[#c96f23]">{money(quote(c.price,profile,prices[c.id]??''))}</b></div>)}</div>}</div></div>}
function PriceSettings({profile,set,close}){const f=(k,v)=>set(p=>({...p,[k]:v}));return <Modal close={close} title="报价与联系方式"><div className="space-y-4"><label className="block text-sm">销售称呼<input value={profile.name} onChange={e=>f('name',e.target.value)} className="mt-2 w-full rounded-xl bg-stone-50 px-3 py-2.5"/></label><label className="block text-sm">联系方式<input value={profile.phone} onChange={e=>f('phone',e.target.value)} className="mt-2 w-full rounded-xl bg-stone-50 px-3 py-2.5"/></label><div className="grid grid-cols-2 gap-3"><label className="text-sm">加价方式<select value={profile.mode} onChange={e=>f('mode',e.target.value)} className="mt-2 w-full rounded-xl bg-stone-50 px-3 py-2.5"><option value="fixed">固定加价</option><option value="rate">百分比加价</option></select></label><label className="text-sm">加价数值<input type="number" value={profile.markup} onChange={e=>f('markup',e.target.value)} className="mt-2 w-full rounded-xl bg-stone-50 px-3 py-2.5"/></label></div><label className="block text-sm">价格尾数<select value={profile.ending} onChange={e=>f('ending',e.target.value)} className="mt-2 w-full rounded-xl bg-stone-50 px-3 py-2.5"><option value="none">不处理</option><option value="10">取整到十元</option><option value="99">调整为 xx99</option><option value="100">取整到百元</option></select></label><button onClick={close} className="w-full rounded-xl bg-[#183f32] py-3 text-white">保存设置</button></div></Modal>}
function SharePreview({cats,profile,prices,close,notify}){const copy=async()=>{await navigator.clipboard.writeText('演示链接：正式版将由服务端生成不可猜测、可关闭的专属链接');notify('演示链接说明已复制');};return <Modal close={close} title="客户展示页预览" wide><div className="rounded-2xl bg-[#183f32] p-6 text-white"><small className="text-white/60">由 {profile.name} 为你整理</small><h3 className="mt-2 text-2xl font-semibold">为你挑选的猫咪</h3><p className="mt-2 text-sm text-white/70">联系方式：{profile.phone}</p></div><div className="mt-4 grid sm:grid-cols-2 gap-3">{cats.map(c=><div key={c.id} className="rounded-xl border border-stone-200 p-4"><b>{c.breed} · {c.color}</b><p className="mt-1 text-sm text-stone-500">{c.gender} · {ageText(c.age)} · {c.city||'城市待补充'}</p><strong className="mt-3 block text-[#c96f23]">{money(quote(c.price,profile,prices[c.id]??''))}</strong></div>)}</div><button onClick={copy} className="mt-5 w-full rounded-xl bg-[#183f32] py-3 text-white flex justify-center gap-2"><Share2 size={17}/>生成专属链接</button></Modal>}
function Modal({close,title,children,wide=false}){return <div className="fixed inset-0 z-50 bg-stone-950/55 p-4 grid place-items-center" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className={`max-h-[90vh] overflow-y-auto w-full ${wide?'max-w-2xl':'max-w-md'} rounded-2xl bg-white shadow-2xl`}><div className="sticky top-0 bg-white flex justify-between border-b border-stone-100 p-5"><b>{title}</b><button onClick={close}><X size={19}/></button></div><div className="p-5">{children}</div></div></div>}
function Video({cat,close}){const [i,setI]=useState(0);if(!cat.videos?.length)return null;return <div className="fixed inset-0 z-50 bg-black/85 p-4 grid place-items-center"><div className="w-full max-w-4xl"><div className="mb-3 flex justify-between text-white"><b>{cat.breed} · {cat.id}</b><button onClick={close}><X/></button></div><video key={cat.videos[i].url} src={cat.videos[i].url} controls playsInline className="w-full max-h-[78vh] bg-black rounded-xl"/>{cat.videos.length>1&&<div className="mt-3 flex gap-2">{cat.videos.map((v,n)=><button key={v.url} onClick={()=>setI(n)} className={`rounded-lg px-3 py-2 text-sm ${i===n?'bg-orange-500 text-white':'bg-white'}`}>视频 {n+1}</button>)}</div>}</div></div>}
function Photo({cat,close}){const images=cat.images?.length?cat.images:[cat.image].filter(Boolean),[i,setI]=useState(0);return <div className="fixed inset-0 z-50 bg-black/90 p-4 flex items-center justify-center"><button className="absolute top-5 right-5 text-white" onClick={close}><X/></button>{images.length?<div className="relative w-full max-w-5xl flex justify-center"><img src={images[i]} className="max-h-[85vh] object-contain" alt="猫咪大图"/>{images.length>1&&<><button onClick={()=>setI((i-1+images.length)%images.length)} className="absolute left-0 top-1/2 text-white"><ChevronLeft size={35}/></button><button onClick={()=>setI((i+1)%images.length)} className="absolute right-0 top-1/2 text-white"><ChevronRight size={35}/></button></>}</div>:<ImageOff className="text-white"/>}</div>}
